### ISSUE TITLE
How to support multi client connections for one server?

### ISSUE THREAD

**Issue by yanjunz** [jlmessenger/NetSocket#1]
I want to launch more than one clients to connect to one server.

**Comment by jlmessenger** [comment]
This library was designed for programs that needed sustained bi-directional communication, where a single client instance would connect to a single server instance on a pre-defined port.
This allows for really simple connection management. Ex: the server app would listen for client A on port 3001, and client B on port 3002, etc. Each client would connect, and once connected the server would stop listening on that port. Then if the connection is broken for any-reason the server would start listening on that port again, and the client can then simply re-establish the connection as soon as it is able.

``` c#
private NetServer serverA = new NetServer();
private NetServer serverB = new NetServer();

public Setup() {
  // ... setup event handlers... 
  this.serverA.Listen(3001);
  this.serverB.Listen(3002);
}
```

If your trying to write something like a chat-room application, where clients each connect and disconnect at random - that is not supported due to the way the connection state management is written. The current server code, once it accepts a connection binds it to a single `this.socket` property and has a single incoming message buffer.
https://github.com/jlmessenger/NetSocket/blob/master/NetSocket/NetSocket.cs#L757

As the library is under the LGPL, you are free to modify the source code for your needs.
You could create a new class called `NetConnection` that can hold an individual socket, connection state and incoming message buffer. Then modify the server `Accept()` method to instantiate an instance of that class and attach it to a `List<NetConnection>`. You'd also need some clean-up code to ensure that as each NetConnection is closed it gets removed from the list, and on server `Close` you could iterate over the List and close each open connection.

Obviously this leaves alot of important details out - including the definition of NetConnection object, but may demonstrate the basic idea.

``` c#
protected List<NetConnection> connections = new List<NetConnection>();
...
public void Accept(Socket client) {
  NetConnection connection = new NetConnection(client);
  this.connections.Add(connection);
}
...
public void Close(string reason) {
  foreach (var connection in this.connections) {
    connection.Close(reason);
  }
}
```

**Comment by yanjunz** [comment]
NetConnection is what I want, Thanks jlmessenger.
